services:
  - type: web
    name: ptsa-tracker
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: singapore
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: 10000
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --worker-class sync --timeout 120 --log-level info wsgi:app
