services:
  - type: web
    name: ptsa-tracker
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
