services:
  - type: web
    name: ptsa-tracker
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: singapore
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///app/instance/ptsa.db
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: 10000
      # Email Configuration (matching config.py)
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USE_SSL
        value: false
      - key: MAIL_USERNAME
        value: info@ptsa.co.za
      - key: MAIL_PASSWORD
        value: your-app-password-here
      - key: MAIL_DEFAULT_SENDER
        value: PTSA Tracker <info@ptsa.co.za>
      # Upload settings
      - key: UPLOAD_FOLDER
        value: /app/uploads
    healthCheckPath: /
    healthcheckTimeout: 100
    restartPolicyType: ON_FAILURE
    restartPolicyMaxRetries: 10
    autoDeploy: true
