services:
  - type: web
    name: ptsa-tracker
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: singapore
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///app/instance/ptsa.db
      - key: PYTHONPATH
        value: /app
      # Email Configuration (matching your image)
      - key: MAIL_SERVER
        value: mail.ptsa.co.za
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: false
      - key: MAIL_USE_SSL
        value: false
      - key: MAIL_USERNAME
        value: info@ptsa.co.za
      - key: MAIL_PASSWORD
        value: wqMvrJm4VZp
      - key: MAIL_DEFAULT_SENDER
        value: info@ptsa.co.za
      # Upload settings
      - key: UPLOAD_FOLDER
        value: /app/uploads
      # Additional Flask settings
      - key: FLASK_APP
        value: wsgi.py
      - key: WTF_CSRF_ENABLED
        value: true
    healthCheckPath: /health
    autoDeploy: true
